server:
  port: 8080

spring:
  datasource:
    username: Myself
    password: hongzi123
    url: jdbc:mysql://39.106.228.42:3306/Myself?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
#
#mybatis:
#  mapper-locations: classpath:mapping/*Mapper.xml
#  type-aliases-package: com.project.xghk416.pojo.po
#
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.*.*.entity
  global-config:
    db-config:
      id-type: auto

#showSql
logging:
  level:
    com:
      example:
        mapper: debug